### ISSUE TITLE
新岛

### ISSUE THREAD

**Issue by smyluke** [alan-best/Box3-Exploring#2]
新岛代码好奇怪，前面居然发现了一段c语言代码转成了一行的字符串（用\n）
```c
            precision highp float;
            attribute vec2 weight;
            varying highp vec3 position;
            uniform mat4 projection, view;
            uniform vec3 start, end, eye;
            uniform float width, fixedSize;
            uniform bool screenSizeFixed;
            void main () {
                vec3 base = mix(start, end, weight.x);
                vec3 lineDir = end - start;
                vec3 eyeDir = eye - base;
                vec3 normalDir = normalize(cross(lineDir, eyeDir));
                vec3 translation = base;
                vec3 point = width * weight.y * normalDir;
                position = point + translation;

                if (screenSizeFixed) {
                    vec3 offset = base - start;
                    float scale = distance(eye, start);
                    point = width * weight.y * normalDir;
                    position = start + ((point + offset) * scale / fixedSize);
                    gl_Position = projection * view * vec4(position, 1);
                } else {
                    gl_Position = projection * view * vec4(position, 1);
                }
            }
```

搜索旧core的操作（比如setvoxel）是能搜到的，说明还是能用的，但是很分散，可能没有一个core，只有一堆prop

代码的结构还是那样，有一个webpackChunk，一堆数字id和函数，变量名几乎都是一个或两个字母，显然经过混淆

用iframe是聊天框等界面的显示

**Comment by alan-best** [comment]
这个不是c语言，这个是shader着色器，语法好像是glsl

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: smyluke ***@***.***>
Sent: Friday, August 11, 2023 9:59:42 PM
To: alan-best/Box3-Exploring ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [alan-best/Box3-Exploring] 新岛 (Issue #2)


新岛代码好奇怪，前面居然发现了一段c语言代码转成了一行的字符串（用\n）

            precision highp float;
            attribute vec2 weight;
            varying highp vec3 position;
            uniform mat4 projection, view;
            uniform vec3 start, end, eye;
            uniform float width, fixedSize;
            uniform bool screenSizeFixed;
            void main () {
                vec3 base = mix(start, end, weight.x);
                vec3 lineDir = end - start;
                vec3 eyeDir = eye - base;
                vec3 normalDir = normalize(cross(lineDir, eyeDir));
                vec3 translation = base;
                vec3 point = width * weight.y * normalDir;
                position = point + translation;

                if (screenSizeFixed) {
                    vec3 offset = base - start;
                    float scale = distance(eye, start);
                    point = width * weight.y * normalDir;
                    position = start + ((point + offset) * scale / fixedSize);
                    gl_Position = projection * view * vec4(position, 1);
                } else {
                    gl_Position = projection * view * vec4(position, 1);
                }
            }

搜索旧core的操作（比如setvoxel）是能搜到的，说明还是能用的，但是很分散，可能没有一个core，只有一堆prop

代码的结构还是那样，有一个webpackChunk，一堆数字id和函数，变量名几乎都是一个或两个字母，显然经过混淆

用iframe是聊天框等界面的显示

―
